### ISSUE TITLE
Which pattern is better: using an angular service as a middle man or using the selectors?

### ISSUE THREAD

**Issue by rszczypka** [onehungrymind/dashing-angular#1]
I'm just on a way to implement the first app using @ngrx/store and watched your video https://www.youtube.com/watch?v=Y2hKn7skC0c&t=4170s
and then I read the article http://onehungrymind.com/handle-multiple-angular-2-models-ngrx-computed-observables/
and after that I watched another video: https://www.youtube.com/watch?v=pjwVq8B-ZAw

Now the question is: "Which pattern is better: using an angular service as a middle man or using the selectors?"
Or maybe composing both approaches?

The services approach seems to be cleaner but I'm curious to hear your opinion.

**Comment by daBishMan** [comment]
First off, thank you so much for doing this sample and sharing with the community, great work !

I wonder if you can extend this example by using routing https://github.com/ngrx/router-store and maybe a search example.  

Thanks again for the great work.

**Comment by jdgarvey** [comment]
Hey guys,
We plan on addressing some of these things in the future on our blog at onehungrymind.com.
Stay tuned!
