### ISSUE TITLE
Scroll overflow not working

### ISSUE THREAD

**Issue by sughodke** [onehungrymind/dashing-angular#5]
When I load the site on a mobile browser (Safari iOS11) I find that the viewport doesn't fit all the cards and is unable to scroll (like it can on desktop).  

It looks like there is some viewport setting that is causing this?

**Comment by jdgarvey** [comment]
@sughodke 
This happens because Safari handles flex a tad differently than other browsers. 6a75d9561edbdd06e852c57429b80ed570453654 fixes this.

Thanks!
