### ISSUE TITLE
MaterialModule Deprecated and Removed

### ISSUE THREAD

**Issue by marc-gj** [onehungrymind/dashing-angular#6]
Would just like to point out that MaterialModule has been deprecated and removed and now causes compilation errors. The way to work around that is to go into the package.json file and change 
`"@angular/material": "^2.0.0-beta.8",` to a version that still supports it. I opted to use `"@angular/material": "2.0.0-beta.3",` and it works just fine.

**Comment by jdgarvey** [comment]
Hey @marc-gj, we've updated the repo to the latest versions of Angular (6.x). As a result, we imported all the individual material modules that we need, so we should be good here.

Thanks!
